"use server";

import prisma from "@/lib/prisma";
import { cookies, headers } from "next/headers";

export const getOrCreateUser = async () => {
  const cookieStore = await cookies();
  const headerStore = await headers();

  // Middleware ensures one of these ALWAYS exists now
  const userId = cookieStore.get("liminal_user_id")?.value || headerStore.get("x-liminal-user-id");

  // Safety check just in case middleware failed (shouldn't happen)
  if (!userId) {
    console.error("Middleware failed to generate ID");
    return null;
  }

  try {
    const existingUser = await prisma.user.findUnique({
      where: { id: userId },
      include: {
        _count: {
          select: {
            uplinksInitiated: true,
            uplinksReceived: true,
            broadcast: true,
          },
        },
      },
    });

    if (existingUser) {
      if (new Date() > existingUser.expiresAt) {
        // If expired, delete and return null (Middleware will issue new ID next refresh)
        await prisma.user.delete({ where: { id: userId } });
        // Note: We can't delete the cookie here easily, but the DB record is gone.
        return null;
      }
      return existingUser;
    }

    // CREATE NEW USER
    const fourHoursFromNow = new Date(Date.now() + 4 * 60 * 60 * 1000);

    return await prisma.user.create({
      data: {
        id: userId, // Uses the ID generated by Middleware
        handle: `anon_${userId.slice(0, 8)}`,
        expiresAt: fourHoursFromNow,
      },
    });
  } catch (error) {
    console.error("getOrCreateUser Error:", error);
    return null;
  }
};
